import customtkinter as customtk
from customtkinter import CTkLabel as Label
from customtkinter import CTkFrame as Frame
from customtkinter import CTkButton as Button
from customtkinter import CTkRadioButton as RadioButton
from customtkinter import CTkCheckBox as CheckBox
from customtkinter import CTkEntry as Entry
from customtkinter import CTkTextbox as TextBox
from customtkinter import CTkComboBox as ComboBox
from customtkinter import CTkProgressBar as ProgressBar
from customtkinter import CTkCanvas as Canvas
from customtkinter import CTkFont as Font
from customtkinter import CTkImage as ctkImage
from customtkinter import CTkToplevel as TopLevel
from customtkinter import CTkTabview as TabView
from customtkinter import CTkOptionMenu as OptionMenu
from customtkinter import CTkBaseClass as BaseClass
from customtkinter import CTkInputDialog as InputDialog
from customtkinter import CTkScrollbar as ScrollBar
from customtkinter import CTkSlider as Slider
from customtkinter import CTkSwitch as Switch
from customtkinter import CTkSegmentedButton as SegmentedButton